version: "4.28.0"

services:
  postgres:
    container_name: bank_project
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bank_project
